### ISSUE TITLE
Hashinize the conf_file

### ISSUE THREAD

**Issue by ody** [thbishop/fission#14]
Looking at extracting a bit more information out of the vmx files that represent each vm.  With the intention of using that information in Fog and matching as closely as possible to the attribute data we extracted for the vSphere provider, https://github.com/fog/fog/blob/master/lib/fog/vsphere/models/compute/server.rb#L20-L36.  Worth establishing a way to get arbitrary data out of the vmx rather than making extra methods that will just look like network_info one but with a different regex?

**Comment by thbishop** [comment]
@ody yep, makes sense.  i was thinking of adding functionality similar to this after releasing 0.4.0.

**Comment by thbishop** [comment]
Implemented with 89370c1af83c855b0483749c5bab07e16256afd2 and b755becd53323ed1fd548f8de0f12155821daf4b.  It will be included in 0.5.0.
