### ISSUE TITLE
No longer functional under Ruby 1.8.7

### ISSUE THREAD

**Issue by ody** [thbishop/fission#18]
Commit 0a4be1fd removes fission's compatibility with Ruby 1.8.7 with the use of the key method.  Since I am using fission as a library to add function to other Ruby projects that are staying compatible with both, 1.8.7 and 1.9.2 it would be advantageous and appreciated to stay compatible with both.

**Comment by thbishop** [comment]
Yeah, my bad.  Totally forgot that was 1.9 specific.
