### ISSUE TITLE
moved/renamed vms are not found

### ISSUE THREAD

**Issue by mattray** [thbishop/fission#2]
I have a VMs that have been copied from another machine and renamed. 'fission status' lists by directory name (within Documents/Virtual Machines.localized/), but the .vmx files within those directories do not match the directory names. For example:

Documents/Virtual Machines.localized/ubuntu2-1004.vmwarevm/ubuntu2-1004.vmx
does not exist but
Documents/Virtual Machines.localized/ubuntu2-1004.vmwarevm/Ubuntu1-10.04.vmx
does.

My naive impression is that looking for Documents/Virtual Machines.localized/ubuntu2-1004.vmwarevm/*vmx should work since my directories only contain a single vmx file each.

**Comment by thbishop** [comment]
Can you elaborate a bit more?

Are you experiencing an error when running 'fission status' or just not getting the output you expect?

Perhaps a gist of your terminal session would help.

Thanks.

**Comment by mattray** [comment]
Fission 'status' only works on VMs that have not been moved or
renamed, the rest report 'not running'. The same holds true for
fission 'start', 'stop' and 'suspend'. Here is an example of the
error:

$ fission start ubuntu2-1004
Starting 'ubuntu2-1004'
There was a problem starting the VM.  The error was:
Error: Cannot open VM: /Users/mray/Documents/Virtual
Machines.localized/ubuntu2-1004.vmwarevm/ubuntu2-1004.vmx, The virtual
machine cannot be found

I realize it's a bit of an edge case, but after peeking into the code
I figured you'd know how to fix it faster than I would.

Thanks,
Matt

On Mon, Aug 29, 2011 at 10:05 PM, thbishop
reply@reply.github.com
wrote:

**Comment by thbishop** [comment]
Thanks for the info.  After some testing, I've found multiple aspects of this scenario which seem to cause different issues.

I think the VM specific commands (start, stop, suspend, etc.) should be fixed now.  I've pushed a beta version of fission up to rubygems.

Can you install it and see if you hit any issues?

You can install the beta with:

```
gem install fission --pre
```

As for the status command, it leverages an existing fusion tool which only reports the running commands.  Fission grabs that output and then appends the delta between the running VMs (from the fusion command line tool) and the other VMs that fission found.

If you aren't seeing the expected output with fission status, try running this command and see what you receive:

```
/Library/Application\ Support/VMware\ Fusion/vmrun list
```

**Comment by mattray** [comment]
Seems to work great, thanks!

**Comment by thbishop** [comment]
Nice, I'll go ahead and close this issue.  Feel free to reopen it or submit a new one if you hit any issues.
