### ISSUE TITLE
fission start does not work with VMWare Fusion 4

### ISSUE THREAD

**Issue by danielqo-zz** [thbishop/fission#20]
`fission start VMNAME` implicitly refers to `/Library/Application Support/VMware Fusion/vmrun` VMWare utility to start a given VM. However, since VMWare Fusion 4, `vmrun` is now part of the _VMWare Fusion.app_ bundle (whose current path is `/Applications/VMware Fusion.app/Contents/Library/vmrun`), causing the following error to the `fission start`command:

```
Starting 'FOO_VM'
sh: /Library/Application Support/VMware Fusion/vmrun: No such file or directory
There was a problem starting the VM.  The error was:
```

So, the current best workaround this issue is to create a file named .fissionrc at your home directory (~/.fissionrc) with the following content:

```
vmrun_bin: "/Applications/VMware Fusion.app/Contents/Library/vmrun"
```

This will override the default settings at `fission/config.rb` file.

**Comment by thbishop** [comment]
Hi Daniel,

You're absolutely correct.  I've updated the README (2d5dd3052815ee5214e10e0b7b09f616b6191a10) with information about this.  Hopefully, the update will help others.
