### ISSUE TITLE
Release version 0.5

### ISSUE THREAD

**Issue by sferik** [thbishop/fission#33]
Thanks for merging in all my patches. Is there anything else holding up the 0.5.0 release? I noticed you pushed 0.5.0.beta.1 back in June. It does look like there have been any bug reports with the beta, so maybe it’s time for a final release?

**Comment by thbishop** [comment]
Thanks for the patches. I should have 0.5.0 out later tonight.

**Comment by thbishop** [comment]
0.5.0 released
