### ISSUE TITLE
Use Thor as CLI class

### ISSUE THREAD

**Issue by jedi4ever** [thbishop/fission#7]
https://github.com/wycats/thor is an extremely easy gem to use for the CLI parsing.

It makes to replace the existing CLI options parsing to this.

What do you think?

**Comment by thbishop** [comment]
I would typically expect fission to be installed in the primary ruby workspace for most people (as opposed to a project specific rvm gemset or something similar).  As such, I definitely want to avoid as many conflicts as possible between fission and any other gems which may be installed in the same workspace.  I did look at a number of command line libs, but I didn't feel that any of them provided enough value to out weigh the additional dependency.
